[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"
  functions = "../netlify/functions"

[context.production.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
